import { PlantsDataType } from '@/types';

export const PLANTS: PlantsDataType[] = [
  {
    id: 1,
    title: 'Туя',
    list: [
      {
        id: 1,
        name: '«Aurea Nana»',
        price: '24',
        units: 'шт',
      },
      {
        id: 2,
        name: '«Brabant»',
        price: '23',
        units: 'шт',
      },
      {
        id: 3,
        name: '«Columna»',
        price: '26',
        units: 'шт',
      },
      {
        id: 4,
        name: '«Europe Gold»',
        price: '36',
        units: 'шт',
      },
      {
        id: 5,
        name: '«Globosa»',
        price: '26',
        units: 'шт',
      },
      {
        id: 6,
        name: '«Hoseri»',
        price: '26',
        units: 'шт',
      },
      {
        id: 7,
        name: '«Kornik»',
        price: '26',
        units: 'шт',
      },
      {
        id: 8,
        name: '«Rheingold»',
        price: '26',
        units: 'шт',
      },
      {
        id: 9,
        name: '«Smaragd»',
        price: '20',
        units: 'шт',
      },
      {
        id: 10,
        name: '«Teddy»',
        price: '25',
        units: 'шт',
      },
      {
        id: 11,
        name: '«Даника»',
        price: '23',
        units: 'шт',
      },
    ],
  },
  {
    id: 2,
    title: 'Можжевельник',
    list: [
      {
        id: 1,
        name: '«Blaue Donau»',
        price: '26',
        units: 'шт',
      },
      {
        id: 2,
        name: '«Blue Arrow»',
        price: '26',
        units: 'шт',
      },
      {
        id: 3,
        name: '«Blue Carpet»',
        price: '26',
        units: 'шт',
      },
      {
        id: 4,
        name: '«Blue Start»',
        price: '26',
        units: 'шт',
      },
      {
        id: 5,
        name: '«Green Carpet»',
        price: '26',
        units: 'шт',
      },
      {
        id: 6,
        name: '«Meyeri»',
        price: '26',
        units: 'шт',
      },
      {
        id: 7,
        name: '«Old Gold»',
        price: '26',
        units: 'шт',
      },
      {
        id: 8,
        name: '«Skyrocket»',
        price: '26',
        units: 'шт',
      },
      {
        id: 9,
        name: '«Stricta»',
        price: '25',
        units: 'шт',
      },
      {
        id: 10,
        name: '«Tamariscifolia»',
        price: '23',
        units: 'шт',
      },
      {
        id: 11,
        name: '«Wiltonii»',
        price: '26',
        units: 'шт',
      },
    ],
  },
  {
    id: 3,
    title: 'Хвойные растения',
    list: [
      {
        id: 1,
        name: 'Тинкго Билоба',
        price: '81',
        units: 'шт',
      },
      {
        id: 2,
        name: 'Горная сосна',
        price: '51',
        units: 'шт',
      },
      {
        id: 3,
        name: 'Канадская тсуга',
        price: '46',
        units: 'шт',
      },
      {
        id: 4,
        name: 'Кедровая сосна',
        price: '76',
        units: 'шт',
      },
      {
        id: 5,
        name: 'Кипарисовик «Alumigold»',
        price: '31',
        units: 'шт',
      },
      {
        id: 6,
        name: 'Кипарисовик «Alumii»',
        price: '56',
        units: 'шт',
      },
      {
        id: 7,
        name: 'Кипарисовик «Pendula»',
        price: '53',
        units: 'шт',
      },
      {
        id: 8,
        name: 'Кипарисовик «Бульвар»',
        price: '26',
        units: 'шт',
      },
      {
        id: 9,
        name: 'Пихта корейская',
        price: '56',
        units: 'шт',
      },
      {
        id: 10,
        name: 'Сосна «Compact Gem»',
        price: '60',
        units: 'шт',
      },
      {
        id: 11,
        name: 'Сосна Веймутова',
        price: '36',
        units: 'шт',
      },
      {
        id: 12,
        name: 'Сосна горная «Mops»',
        price: '60',
        units: 'шт',
      },
      {
        id: 13,
        name: 'Сосна обыкновенная «Watereri»',
        price: '76',
        units: 'шт',
      },
      {
        id: 14,
        name: 'Тис «Fastigiata»',
        price: '40',
        units: 'шт',
      },
      {
        id: 15,
        name: 'Тис «Hicksii»',
        price: '40',
        units: 'шт',
      },
      {
        id: 16,
        name: 'Тис «Repandens»',
        price: '40',
        units: 'шт',
      },
      {
        id: 17,
        name: 'Тсуга канадская «Jeddeloh»',
        price: '46',
        units: 'шт',
      },
    ],
  },
  {
    id: 4,
    title: 'Декоративные кустарники',
    list: [
      {
        id: 1,
        name: 'Барбарис «Harlequin»',
        price: '19',
        units: 'шт',
      },
      {
        id: 2,
        name: 'Барбарис «Sunjoy Gold Pillar»',
        price: '19',
        units: 'шт',
      },
      {
        id: 3,
        name: 'Барбарис Тунберга «Erecta»',
        price: '16',
        units: 'шт',
      },
      {
        id: 4,
        name: 'Барбарис Тунберга «Golden Ring»',
        price: '19',
        units: 'шт',
      },
      {
        id: 5,
        name: 'Барбарис Тунберга «Aurea»',
        price: '19',
        units: 'шт',
      },
      {
        id: 6,
        name: 'Барбарис Тунберга «Red Pillar»',
        price: '19',
        units: 'шт',
      },
      {
        id: 7,
        name: 'Бересклет крылатый',
        price: '26',
        units: 'шт',
      },
      {
        id: 8,
        name: 'Бересклет Форчуна «Emerald Gaiety»',
        price: '13',
        units: 'шт',
      },
      {
        id: 9,
        name: 'Бересклет Форчуна «Interbolni»',
        price: '13',
        units: 'шт',
      },
      {
        id: 10,
        name: 'Бересклет Форчуна «Blondy»',
        price: '16',
        units: 'шт',
      },
      {
        id: 11,
        name: 'Бересклет Форчуна «Aureum»',
        price: '36',
        units: 'шт',
      },
      {
        id: 12,
        name: 'Бирючина обыкновенная',
        price: '10',
        units: 'шт',
      },
      {
        id: 13,
        name: 'Буддлея «Black Knight»',
        price: '26',
        units: 'шт',
      },
      {
        id: 14,
        name: 'Буддлея Давида «Border Beauty»',
        price: '26',
        units: 'шт',
      },
      {
        id: 15,
        name: 'Буддлея Давида «Nonho Blue»',
        price: '26',
        units: 'шт',
      },
      {
        id: 17,
        name: 'Буддлея Давида «Purple Emperor»',
        price: '26',
        units: 'шт',
      },
      {
        id: 18,
        name: 'Буддлея Давида «Royal Red»',
        price: '26',
        units: 'шт',
      },
      {
        id: 19,
        name: 'Буддлея Давида «White Profusion»',
        price: '26',
        units: 'шт',
      },
    ],
  },
  {
    id: 5,
    title: 'Декоративные деревья',
    list: [
      {
        id: 1,
        name: 'Бобовник «Золотой дождь»',
        price: '46',
        units: 'шт',
      },
      {
        id: 2,
        name: 'Гинкго Двулопастный',
        price: '91',
        units: 'шт',
      },
      {
        id: 3,
        name: 'Граб Европейский',
        price: '21',
        units: 'шт',
      },
      {
        id: 4,
        name: 'Дуб Черешчатый',
        price: '23',
        units: 'шт',
      },
      {
        id: 5,
        name: 'Ива «Hakuro-Nishiki» (на штамбе)',
        price: '71',
        units: 'шт',
      },
      {
        id: 6,
        name: 'Ива козья «Pendula»',
        price: '71',
        units: 'шт',
      },
      {
        id: 7,
        name: 'Каштан Конский',
        price: '21',
        units: 'шт',
      },
      {
        id: 8,
        name: 'Красный дуб',
        price: '26',
        units: 'шт',
      },
      {
        id: 9,
        name: 'Миндаль на штамбе',
        price: '15.',
        units: 'шт',
      },
      {
        id: 10,
        name: 'Робиния Белая',
        price: '13',
        units: 'шт',
      },
      {
        id: 11,
        name: 'Сумах уксусный «Dissecta»',
        price: '23',
        units: 'шт',
      },
      {
        id: 12,
        name: 'Тюльпановое дерево «Лилеодендрон»',
        price: '12.',
        units: 'шт',
      },
    ],
  },
  {
    id: 6,
    title: 'Хосты',
    list: [
      {
        id: 1,
        name: '«Blue Cadet»',
        price: '13',
        units: 'шт',
      },
      {
        id: 2,
        name: '«Blue Dimples»',
        price: '13',
        units: 'шт',
      },
      {
        id: 3,
        name: '«Cameo»',
        price: '13',
        units: 'шт',
      },
      {
        id: 4,
        name: '«First Frost»',
        price: '13',
        units: 'шт',
      },
      {
        id: 5,
        name: '«Golden Oriole»',
        price: '13',
        units: 'шт',
      },
      {
        id: 6,
        name: '«Grand Marquee»',
        price: '13',
        units: 'шт',
      },
    ],
  },
  {
    id: 7,
    title: 'Сирень',
    list: [
      {
        id: 1,
        name: '«Primrose»',
        price: '31',
        units: 'шт',
      },
      {
        id: 2,
        name: '«Катерина Хавемейер»',
        price: '20',
        units: 'шт',
      },
      {
        id: 3,
        name: '«Конго»',
        price: '20',
        units: 'шт',
      },
      {
        id: 4,
        name: '«Космос»',
        price: '20',
        units: 'шт',
      },
      {
        id: 5,
        name: '«Красавица Москвы»',
        price: '29',
        units: 'шт',
      },
      {
        id: 6,
        name: '«Красная Москва»',
        price: '20',
        units: 'шт',
      },
      {
        id: 7,
        name: '«Мадам Лемуан»',
        price: '20',
        units: 'шт',
      },
      {
        id: 8,
        name: '«Мулатка»',
        price: '29',
        units: 'шт',
      },
      {
        id: 9,
        name: '«Павлинка»',
        price: '20',
        units: 'шт',
      },
      {
        id: 10,
        name: '«Сенсация»',
        price: '23',
        units: 'шт',
      },
      {
        id: 11,
        name: '«Советская артктика»',
        price: '20',
        units: 'шт',
      },
      {
        id: 12,
        name: '«Сумерки»',
        price: '20',
        units: 'шт',
      },
      {
        id: 13,
        name: '«Утро России»',
        price: '20',
        units: 'шт',
      },
    ],
  },
];
