import { PlantsDataType } from '@/types';

export const PLANTS: PlantsDataType[] = [
  {
    id: 1,
    title: 'Туя',
    list: [
      {
        id: 1,
        name: '«Aurea Nana»',
        units: 'шт',
        price: '24 руб',
      },
      {
        id: 2,
        name: '«Brabant»',
        units: 'шт',
        price: '23 руб',
      },
      {
        id: 3,
        name: '«Columna»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 4,
        name: '«Europe Gold»',
        units: 'шт',
        price: '36 руб',
      },
      {
        id: 5,
        name: '«Globosa»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 6,
        name: '«Hoseri»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 7,
        name: '«Kornik»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 8,
        name: '«Rheingold»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 9,
        name: '«Smaragd»',
        units: 'шт',
        price: '20 руб',
      },
      {
        id: 10,
        name: '«Teddy»',
        units: 'шт',
        price: '25 руб',
      },
      {
        id: 11,
        name: '«Даника»',
        units: 'шт',
        price: '23 руб',
      },
    ],
  },
  {
    id: 2,
    title: 'Можжевельник',
    list: [
      {
        id: 1,
        name: '«Blaue Donau»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 2,
        name: '«Blue Arrow»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 3,
        name: '«Blue Carpet»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 4,
        name: '«Blue Start»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 5,
        name: '«Green Carpet»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 6,
        name: '«Meyeri»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 7,
        name: '«Old Gold»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 8,
        name: '«Skyrocket»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 9,
        name: '«Stricta»',
        units: 'шт',
        price: '25 руб',
      },
      {
        id: 10,
        name: '«Tamariscifolia»',
        units: 'шт',
        price: '23 руб',
      },
      {
        id: 11,
        name: '«Wiltonii»',
        units: 'шт',
        price: '26 руб',
      },
    ],
  },
  {
    id: 3,
    title: 'Хвойные растения',
    list: [
      {
        id: 1,
        name: 'Тинкго Билоба',
        units: 'шт',
        price: '81 руб',
      },
      {
        id: 2,
        name: 'Горная сосна',
        units: 'шт',
        price: '51 руб',
      },
      {
        id: 3,
        name: 'Канадская тсуга',
        units: 'шт',
        price: '46 руб',
      },
      {
        id: 4,
        name: 'Кедровая сосна',
        units: 'шт',
        price: '76 руб',
      },
      {
        id: 5,
        name: 'Кипарисовик «Alumigold»',
        units: 'шт',
        price: '31 руб',
      },
      {
        id: 6,
        name: 'Кипарисовик «Alumii»',
        units: 'шт',
        price: '56 руб',
      },
      {
        id: 7,
        name: 'Кипарисовик «Pendula»',
        units: 'шт',
        price: '53 руб',
      },
      {
        id: 8,
        name: 'Кипарисовик «Бульвар»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 9,
        name: 'Пихта корейская',
        units: 'шт',
        price: '56 руб',
      },
      {
        id: 10,
        name: 'Сосна «Compact Gem»',
        units: 'шт',
        price: '60 руб',
      },
      {
        id: 11,
        name: 'Сосна Веймутова',
        units: 'шт',
        price: '36 руб',
      },
      {
        id: 12,
        name: 'Сосна горная «Mops»',
        units: 'шт',
        price: '60 руб',
      },
      {
        id: 13,
        name: 'Сосна обыкновенная «Watereri»',
        units: 'шт',
        price: '76 руб',
      },
      {
        id: 14,
        name: 'Тис «Fastigiata»',
        units: 'шт',
        price: '40 руб',
      },
      {
        id: 15,
        name: 'Тис «Hicksii»',
        units: 'шт',
        price: '40 руб',
      },
      {
        id: 16,
        name: 'Тис «Repandens»',
        units: 'шт',
        price: '40 руб',
      },
      {
        id: 17,
        name: 'Тсуга канадская «Jeddeloh»',
        units: 'шт',
        price: '46 руб',
      },
    ],
  },
  {
    id: 4,
    title: 'Декоративные кустарники',
    list: [
      {
        id: 1,
        name: 'Барбарис «Harlequin»',
        units: 'шт',
        price: '19 руб',
      },
      {
        id: 2,
        name: 'Барбарис «Sunjoy Gold Pillar»',
        units: 'шт',
        price: '19 руб',
      },
      {
        id: 3,
        name: 'Барбарис Тунберга «Erecta»',
        units: 'шт',
        price: '16 руб',
      },
      {
        id: 4,
        name: 'Барбарис Тунберга «Golden Ring»',
        units: 'шт',
        price: '19 руб',
      },
      {
        id: 5,
        name: 'Барбарис Тунберга «Aurea»',
        units: 'шт',
        price: '19 руб',
      },
      {
        id: 6,
        name: 'Барбарис Тунберга «Red Pillar»',
        units: 'шт',
        price: '19 руб',
      },
      {
        id: 7,
        name: 'Бересклет крылатый',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 8,
        name: 'Бересклет Форчуна «Emerald Gaiety»',
        units: 'шт',
        price: '13 руб',
      },
      {
        id: 9,
        name: 'Бересклет Форчуна «Interbolni»',
        units: 'шт',
        price: '13 руб',
      },
      {
        id: 10,
        name: 'Бересклет Форчуна «Blondy»',
        units: 'шт',
        price: '16 руб',
      },
      {
        id: 11,
        name: 'Бересклет Форчуна «Aureum»',
        units: 'шт',
        price: '36 руб',
      },
      {
        id: 12,
        name: 'Бирючина обыкновенная',
        units: 'шт',
        price: '10 руб',
      },
      {
        id: 13,
        name: 'Буддлея «Black Knight»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 14,
        name: 'Буддлея Давида «Border Beauty»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 15,
        name: 'Буддлея Давида «Nonho Blue»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 17,
        name: 'Буддлея Давида «Purple Emperor»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 18,
        name: 'Буддлея Давида «Royal Red»',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 19,
        name: 'Буддлея Давида «White Profusion»',
        units: 'шт',
        price: '26 руб',
      },
    ],
  },
  {
    id: 5,
    title: 'Декоративные деревья',
    list: [
      {
        id: 1,
        name: 'Бобовник «Золотой дождь»',
        units: 'шт',
        price: '46 руб',
      },
      {
        id: 2,
        name: 'Гинкго Двулопастный',
        units: 'шт',
        price: '91 руб',
      },
      {
        id: 3,
        name: 'Граб Европейский',
        units: 'шт',
        price: '21 руб',
      },
      {
        id: 4,
        name: 'Дуб Черешчатый',
        units: 'шт',
        price: '23 руб',
      },
      {
        id: 5,
        name: 'Ива «Hakuro-Nishiki» (на штамбе)',
        units: 'шт',
        price: '71 руб',
      },
      {
        id: 6,
        name: 'Ива козья «Pendula»',
        units: 'шт',
        price: '71 руб',
      },
      {
        id: 7,
        name: 'Каштан Конский',
        units: 'шт',
        price: '21 руб',
      },
      {
        id: 8,
        name: 'Красный дуб',
        units: 'шт',
        price: '26 руб',
      },
      {
        id: 9,
        name: 'Миндаль на штамбе',
        units: 'шт',
        price: '15 руб',
      },
      {
        id: 10,
        name: 'Робиния Белая',
        units: 'шт',
        price: '13 руб',
      },
      {
        id: 11,
        name: 'Сумах уксусный «Dissecta»',
        units: 'шт',
        price: '23 руб',
      },
      {
        id: 12,
        name: 'Тюльпановое дерево «Лилеодендрон»',
        units: 'шт',
        price: '12 руб',
      },
    ],
  },
  {
    id: 6,
    title: 'Хосты',
    list: [
      {
        id: 1,
        name: '«Blue Cadet»',
        units: 'шт',
        price: '13 руб',
      },
      {
        id: 2,
        name: '«Blue Dimples»',
        units: 'шт',
        price: '13 руб',
      },
      {
        id: 3,
        name: '«Cameo»',
        units: 'шт',
        price: '13 руб',
      },
      {
        id: 4,
        name: '«First Frost»',
        units: 'шт',
        price: '13 руб',
      },
      {
        id: 5,
        name: '«Golden Oriole»',
        units: 'шт',
        price: '13 руб',
      },
      {
        id: 6,
        name: '«Grand Marquee»',
        units: 'шт',
        price: '13 руб',
      },
    ],
  },
  {
    id: 7,
    title: 'Сирень',
    list: [
      {
        id: 1,
        name: '«Primrose»',
        units: 'шт',
        price: '31 руб',
      },
      {
        id: 2,
        name: '«Катерина Хавемейер»',
        units: 'шт',
        price: '20 руб',
      },
      {
        id: 3,
        name: '«Конго»',
        units: 'шт',
        price: '20 руб',
      },
      {
        id: 4,
        name: '«Космос»',
        units: 'шт',
        price: '20 руб',
      },
      {
        id: 5,
        name: '«Красавица Москвы»',
        units: 'шт',
        price: '29 руб',
      },
      {
        id: 6,
        name: '«Красная Москва»',
        units: 'шт',
        price: '20 руб',
      },
      {
        id: 7,
        name: '«Мадам Лемуан»',
        units: 'шт',
        price: '20 руб',
      },
      {
        id: 8,
        name: '«Мулатка»',
        units: 'шт',
        price: '29 руб',
      },
      {
        id: 9,
        name: '«Павлинка»',
        units: 'шт',
        price: '20 руб',
      },
      {
        id: 10,
        name: '«Сенсация»',
        units: 'шт',
        price: '23 руб',
      },
      {
        id: 11,
        name: '«Советская артктика»',
        units: 'шт',
        price: '20 руб',
      },
      {
        id: 12,
        name: '«Сумерки»',
        units: 'шт',
        price: '20 руб',
      },
      {
        id: 13,
        name: '«Утро России»',
        units: 'шт',
        price: '20 руб',
      },
    ],
  },
];
